/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KzButton {
        "isFullWidth": boolean;
        "label": string;
        "variant": "primary" | "default";
    }
}
declare global {
    interface HTMLKzButtonElement extends Components.KzButton, HTMLStencilElement {
    }
    var HTMLKzButtonElement: {
        prototype: HTMLKzButtonElement;
        new (): HTMLKzButtonElement;
    };
    interface HTMLElementTagNameMap {
        "kz-button": HTMLKzButtonElement;
    }
}
declare namespace LocalJSX {
    interface KzButton {
        "isFullWidth"?: boolean;
        "label"?: string;
        "variant"?: "primary" | "default";
    }
    interface IntrinsicElements {
        "kz-button": KzButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kz-button": LocalJSX.KzButton & JSXBase.HTMLAttributes<HTMLKzButtonElement>;
        }
    }
}
